# Generated by Django 4.2.14 on 2024-07-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contacto_mensaje_cifrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
    ]
